[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bounty_escrow = "BAZdzAroYAZYNrt8PxpxbvrA87wdMighpPSzS4NcDaYY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
